# Generated by Django 3.2 on 2021-11-28 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='newsImage/')),
                ('heading', models.CharField(max_length=500)),
                ('intro_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='RegisterData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=500)),
                ('last_name', models.CharField(max_length=500)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('sex', models.CharField(max_length=10)),
                ('age', models.IntegerField()),
                ('state', models.CharField(max_length=200)),
                ('local_govt', models.CharField(max_length=200)),
            ],
        ),
    ]
