# Generated by Django 3.2 on 2021-11-30 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='unit',
            field=models.CharField(default='', max_length=250),
        ),
        migrations.AddField(
            model_name='registerdata',
            name='ward',
            field=models.CharField(default='', max_length=250),
        ),
    ]
