# Generated by Django 3.2 on 2021-12-01 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0002_auto_20211129_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='stateOfOrigin',
            field=models.CharField(default='', max_length=350),
        ),
    ]
