# Generated by Django 3.2 on 2021-12-06 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainApp', '0003_registerdata_stateoforigin'),
    ]

    operations = [
        migrations.AddField(
            model_name='registerdata',
            name='voters_identification_number',
            field=models.CharField(default='NiL', max_length=350),
        ),
    ]
